/* eslint-disable react/no-unescaped-entities */
import { useState } from "react";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillLinkedin, AiOutlineMail, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import myphoto from "../public/myPic.jpg";


export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bryan Zikhayi's Web Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white dark:bg-gray-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">Bryan Zikhayi's web profile</h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-2xl">
                {!darkMode ? (
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} />
                ) : (
                  <BsFillSunFill
                    className="text-white"
                    onClick={() => setDarkMode(!darkMode)}
                  />
                )}
              </li>
            </ul>
          </nav>
          
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-400 font-medium md:text-6xl">
              Bryan Zikhayi
            </h2>
            <h3 className="text-2xl dark:text-white py-2 md:text-3xl">
              Front End Developer / Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              
              I recently graduated from Wits University with a degree in Computer Science. During my studies, I developed a strong foundation in programming languages such as Java, Python, and C++, as well as experience working with web development technologies such as ReactJS, MongoDB, SQL, Postman, HTML, CSS, and JavaScript.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am excited about the prospect of joining SovTech as a developer because of the company's reputation for innovation and commitment to using technology to drive positive change. I am passionate about using technology to solve real-world problems, and I believe that SovTech's focus on using technology to drive social impact aligns with my personal values. I am particularly interested in the company's work in the fintech space and the potential for technology to improve access to financial services for underrepresented communities.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As a recent graduate, I am eager to apply my knowledge and skills to real-world projects and to continue learning and growing as a developer. I am a self-motivated individual with a strong work ethic and a commitment to excellence. I am confident that my technical skills, creativity, and passion for technology make me a strong fit for a developer position at SovTech, and I am excited about the opportunity to work with a team of talented and like-minded individuals.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="//linkedin.com/in/bryan-zikhayi-4707521aa/">
              <AiFillLinkedin />
            </a>
            <a href="mailto:bryanzikhayi@gmail.com">
              <AiOutlineMail />
            </a>
            <a href="//github.com/Bryan-Biggie">
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:h-96 md:w-96">
            <Image src={myphoto} alt="myphoto" className="w-80 md:w-96" />
          </div>
        </section>
      </main>
    </div>
  );
}
